// Generated by scripts/generate-android-design-tokens.mjs. Do not edit by hand.
package com.fish.android.core.designsystem.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.colorspace.ColorSpaces
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin

internal data class GeneratedColorToken(val light: Color, val dark: Color)

private fun oklch(lightness: Double, chroma: Double, hueDegrees: Double, alpha: Double): Color {
    val hueRadians = hueDegrees * PI / 180.0
    return Color(
        lightness.toFloat(),
        (chroma * cos(hueRadians)).toFloat(),
        (chroma * sin(hueRadians)).toFloat(),
        alpha.toFloat(),
        ColorSpaces.Oklab,
    )
}

internal object GeneratedColors {
    val Background = GeneratedColorToken(oklch(0.98, 0.0, 0.0, 1.0), oklch(0.15, 0.0, 0.0, 1.0))
    val Surface = GeneratedColorToken(oklch(0.99, 0.0, 0.0, 1.0), oklch(0.18, 0.0, 0.0, 1.0))
    val SurfaceAlt = GeneratedColorToken(oklch(0.96, 0.0, 0.0, 1.0), oklch(0.2, 0.0, 0.0, 1.0))
    val InteractiveHover = GeneratedColorToken(oklch(0.94, 0.0, 0.0, 1.0), oklch(0.22, 0.0, 0.0, 1.0))
    val InteractiveActive = GeneratedColorToken(oklch(0.92, 0.0, 0.0, 1.0), oklch(0.25, 0.0, 0.0, 1.0))
    val Avatar = GeneratedColorToken(oklch(0.9, 0.0, 0.0, 1.0), oklch(0.3, 0.0, 0.0, 1.0))
    val Selected = GeneratedColorToken(oklch(0.88, 0.0, 0.0, 1.0), oklch(0.33, 0.0, 0.0, 1.0))
    val Border = GeneratedColorToken(oklch(0.64, 0.0, 0.0, 1.0), oklch(0.55, 0.0, 0.0, 1.0))
    val BorderStrong = GeneratedColorToken(oklch(0.55, 0.0, 0.0, 1.0), oklch(0.65, 0.0, 0.0, 1.0))
    val Divider = GeneratedColorToken(oklch(0.15, 0.0, 0.0, 0.1), oklch(0.98, 0.0, 0.0, 0.12))
    val Primary = GeneratedColorToken(oklch(0.15, 0.0, 0.0, 1.0), oklch(0.98, 0.0, 0.0, 1.0))
    val PrimaryPressed = GeneratedColorToken(oklch(0.25, 0.0, 0.0, 1.0), oklch(0.9, 0.0, 0.0, 1.0))
    val OnPrimary = GeneratedColorToken(oklch(0.98, 0.0, 0.0, 1.0), oklch(0.15, 0.0, 0.0, 1.0))
    val Foreground = GeneratedColorToken(oklch(0.15, 0.0, 0.0, 1.0), oklch(0.97, 0.0, 0.0, 1.0))
    val Body = GeneratedColorToken(oklch(0.32, 0.0, 0.0, 1.0), oklch(0.88, 0.0, 0.0, 1.0))
    val Muted = GeneratedColorToken(oklch(0.5, 0.0, 0.0, 1.0), oklch(0.68, 0.0, 0.0, 1.0))
    val SkeletonAuthor = GeneratedColorToken(oklch(0.82, 0.0, 0.0, 1.0), oklch(0.38, 0.0, 0.0, 1.0))
    val Notice = GeneratedColorToken(oklch(0.4, 0.0, 0.0, 1.0), oklch(0.8, 0.0, 0.0, 1.0))
    val Error = GeneratedColorToken(oklch(0.45, 0.14, 20.0, 1.0), oklch(0.78, 0.11, 20.0, 1.0))
    val Warning = GeneratedColorToken(oklch(0.42, 0.12, 80.0, 1.0), oklch(0.78, 0.12, 80.0, 1.0))
    val Success = GeneratedColorToken(oklch(0.4, 0.11, 150.0, 1.0), oklch(0.75, 0.12, 150.0, 1.0))
    val SuccessPressed = GeneratedColorToken(oklch(0.34, 0.11, 150.0, 1.0), oklch(0.82, 0.1, 150.0, 1.0))
    val PresenceOnline = GeneratedColorToken(oklch(0.4, 0.11, 150.0, 1.0), oklch(0.75, 0.12, 150.0, 1.0))
    val PresenceIdle = GeneratedColorToken(oklch(0.45, 0.12, 85.0, 1.0), oklch(0.78, 0.12, 85.0, 1.0))
    val PresenceAway = GeneratedColorToken(oklch(0.45, 0.13, 55.0, 1.0), oklch(0.76, 0.12, 55.0, 1.0))
    val PresenceBusy = GeneratedColorToken(oklch(0.45, 0.12, 20.0, 1.0), oklch(0.77, 0.1, 20.0, 1.0))
    val PresenceOffline = GeneratedColorToken(oklch(0.46, 0.0, 0.0, 1.0), oklch(0.7, 0.0, 0.0, 1.0))
    val Scrim = GeneratedColorToken(oklch(0.15, 0.0, 0.0, 0.4), oklch(0.0, 0.0, 0.0, 0.6))
}

internal object GeneratedSpacing {
    val ThreeXs = 2.dp
    val TwoXs = 4.dp
    val Nudge = 6.dp
    val Xs = 8.dp
    val Compact = 10.dp
    val Sm = 12.dp
    val FieldY = 14.dp
    val Md = 16.dp
    val Page = 20.dp
    val Lg = 24.dp
    val Xl = 40.dp
    val TwoXl = 48.dp
    val ThreeXl = 72.dp
    val FourXl = 112.dp
}

internal object GeneratedRadii {
    val Card = 16.dp
    val Chat = 16.dp
    val Control = 12.dp
    val ChatInner = 4.dp
    val Pill = 999.dp
}

internal object GeneratedSizes {
    val TouchTarget = 48.dp
    val PrimaryControl = 56.dp
    val IconGlyph = 20.dp
    val PresenceIndicatorSmall = 14.dp
    val ChatHeader = 64.dp
    val ComposerMin = 56.dp
    val ComposerMax = 160.dp
    val ConversationRail = 304.dp
    val ChatContentMax = 720.dp
    val AvatarSmall = 32.dp
    val AvatarMedium = 40.dp
    val AvatarLarge = 72.dp
    val Badge = 20.dp
    val BadgeSlot = 40.dp
    val PaginationSlot = 112.dp
}

internal object GeneratedType {
    val DisplaySize = 32.sp
    val DisplayLineHeight = 35.2.sp
    val HeadingSize = 20.sp
    val HeadingLineHeight = 23.sp
    val BodySize = 17.sp
    val BodyLineHeight = 26.35.sp
    val UiSize = 15.sp
    val UiLineHeight = 22.5.sp
    val LabelSize = 14.sp
    val LabelLineHeight = 20.3.sp
    val CaptionSize = 13.sp
    val CaptionLineHeight = 18.2.sp
}

internal object GeneratedDurations {
    const val Reduced = 0
    const val Fade = 200
    const val Message = 200
    const val Typing = 1200
    const val TypingDelayShort = 150
    const val TypingDelayLong = 300
    const val Reaction = 180
    const val Progress = 500
    const val Skeleton = 1400
}

internal object GeneratedLayout {
    const val MessageMaxWidthFraction = 0.85f
    val TwoPaneBreakpoint = 840.dp
}
